version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  api:
    build: ./api
    container_name: invoice_api
    ports:
      - "8080:8080"
    depends_on:
      - broker
    environment:
      INVOICE_TO_PROCESS_TOPIC: invoice.to.process
      KAFKA_HOST: broker:29092

  processor:
    build: ./processor
    container_name: invoice_processor
    depends_on:
      - broker
    environment:
      KAFKA_HOST: broker:29092
      CONSUMER_GROUP: processor.consumer.1
      INJESTION_TYPE: earliest
      INVOICE_TO_PROCESS_TOPIC: invoice.to.process
      INVOICE_PROCESSED_TOPIC: invoice.processed

  post-processor:
    build: ./post-processor
    container_name: invoice_post_processor
    depends_on:
      - broker
    environment:
      KAFKA_HOST: broker:29092
      CONSUMER_GROUP: post.processor.consumer.1
      INJESTION_TYPE: earliest
      INVOICE_PROCESSED_TOPIC: invoice.processed
    volumes:
      - "./database:/go/delivery/database"
