FROM golang
ARG KAFKA_HOST
ARG CONSUMER_GROUP
ARG INJESTION_TYPE
ARG INVOICE_PROCESSED_TOPIC
WORKDIR /go/delivery
COPY . .
RUN go mod download
RUN go build -o /post-processor
CMD [ "/post-processor" ]